var namespace_c_g_u_l_1_1_assimp =
[
    [ "Animation", "class_c_g_u_l_1_1_assimp_1_1_animation.html", "class_c_g_u_l_1_1_assimp_1_1_animation" ],
    [ "Bone", "class_c_g_u_l_1_1_assimp_1_1_bone.html", "class_c_g_u_l_1_1_assimp_1_1_bone" ],
    [ "Camera", "class_c_g_u_l_1_1_assimp_1_1_camera.html", "class_c_g_u_l_1_1_assimp_1_1_camera" ],
    [ "ExportBlob", "class_c_g_u_l_1_1_assimp_1_1_export_blob.html", "class_c_g_u_l_1_1_assimp_1_1_export_blob" ],
    [ "Exporter", "class_c_g_u_l_1_1_assimp_1_1_exporter.html", "class_c_g_u_l_1_1_assimp_1_1_exporter" ],
    [ "ExportFormatDesc", "class_c_g_u_l_1_1_assimp_1_1_export_format_desc.html", "class_c_g_u_l_1_1_assimp_1_1_export_format_desc" ],
    [ "Face", "class_c_g_u_l_1_1_assimp_1_1_face.html", "class_c_g_u_l_1_1_assimp_1_1_face" ],
    [ "Importer", "class_c_g_u_l_1_1_assimp_1_1_importer.html", "class_c_g_u_l_1_1_assimp_1_1_importer" ],
    [ "Light", "class_c_g_u_l_1_1_assimp_1_1_light.html", "class_c_g_u_l_1_1_assimp_1_1_light" ],
    [ "Material", "class_c_g_u_l_1_1_assimp_1_1_material.html", "class_c_g_u_l_1_1_assimp_1_1_material" ],
    [ "MaterialProperty", "class_c_g_u_l_1_1_assimp_1_1_material_property.html", "class_c_g_u_l_1_1_assimp_1_1_material_property" ],
    [ "Mesh", "class_c_g_u_l_1_1_assimp_1_1_mesh.html", "class_c_g_u_l_1_1_assimp_1_1_mesh" ],
    [ "MeshAnimation", "class_c_g_u_l_1_1_assimp_1_1_mesh_animation.html", "class_c_g_u_l_1_1_assimp_1_1_mesh_animation" ],
    [ "MeshKey", "struct_c_g_u_l_1_1_assimp_1_1_mesh_key.html", "struct_c_g_u_l_1_1_assimp_1_1_mesh_key" ],
    [ "Node", "class_c_g_u_l_1_1_assimp_1_1_node.html", "class_c_g_u_l_1_1_assimp_1_1_node" ],
    [ "NodeAnimation", "class_c_g_u_l_1_1_assimp_1_1_node_animation.html", "class_c_g_u_l_1_1_assimp_1_1_node_animation" ],
    [ "QuatKey", "struct_c_g_u_l_1_1_assimp_1_1_quat_key.html", "struct_c_g_u_l_1_1_assimp_1_1_quat_key" ],
    [ "Scene", "class_c_g_u_l_1_1_assimp_1_1_scene.html", "class_c_g_u_l_1_1_assimp_1_1_scene" ],
    [ "Texture", "class_c_g_u_l_1_1_assimp_1_1_texture.html", "class_c_g_u_l_1_1_assimp_1_1_texture" ],
    [ "UVTransform", "class_c_g_u_l_1_1_assimp_1_1_u_v_transform.html", "class_c_g_u_l_1_1_assimp_1_1_u_v_transform" ],
    [ "VectorKey", "struct_c_g_u_l_1_1_assimp_1_1_vector_key.html", "struct_c_g_u_l_1_1_assimp_1_1_vector_key" ],
    [ "VertexWeight", "class_c_g_u_l_1_1_assimp_1_1_vertex_weight.html", "class_c_g_u_l_1_1_assimp_1_1_vertex_weight" ]
];